### ISSUE TITLE
Preventing replay/misinterpretation attacks when using VPs

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/waci-presentation-exchange#10] opened 2021-05-03 21:00 UTC
As a holder, I want to make sure that even if my Verifiable Presentation is stolen, such as through a man-in-the-middle attack, that it cannot be used for any other purpose than the one I intended. I want the ability to scope the VP's interaction to a granular level across both LD-Proof and JWT reprs.

Currently the spec allows for a `challengeToken` tied to a particular interaction, but if an attacker finds my VP, they may try to reuse this with other protocols that don't acknowledge `challengeToken` and interpret the VP as a broad use item.

Possible approaches that may help:
(1) Assume all other protocols have their own challenge token system to bind VPs, and no exchange protocols will exist without this (or at all). Then this becomes a non-issue.
(2) Add additional scoping metadata as part of VP to reduce the chance of misinterpretation, such as by adding scoping elements including but not implemented to domain, target recipient, presentation purpose (what signing request type codebook can we piggyback?), etc.
(3) Bind the VC to the session so it can't be used with any other sessions (maybe DIDComm has this black magic)?

**Comment by OR13** [comment] 2021-05-24 18:28
>  I want the ability to scope the VP's interaction to a granular level across both LD-Proof and JWT reprs.

This is out of the box if your VP is W3C VC Data Model Compliant.

I suggest closing this issue, since it is solved for by having a VP that is spec conformant.

see https://w3c.github.io/vc-data-model/#example-2-a-simple-example-of-a-verifiable-presentation

**Comment by wyc** [comment] 2021-05-24 21:18
That is true for LD-Proof VPs, but not necessarily so for JWT-based ones:

From https://w3c.github.io/vc-data-model/#presentations-0
> If present, the value of the proof property ensures that the presentation is verifiable. For details related to the use of this property, see Section § 4.7 Proofs (Signatures).
...
> The contents of the proof property are proofs, as described by the Linked Data Proofs [LD-PROOFS] specification. An example of a verifiable presentation using the JWT proof mechanism is given in section § 6.3.1 JSON Web Token.

In the JWT representation guidelines, there's no requirement for `proof` to contain things like `domain` or `challenge`. 
https://w3c.github.io/vc-data-model/#json-web-token

Would you be open to suggesting (using SHOULD) that VPs used in WACI-PEX to implement a `proof` section containing challenge + domain or similar JWT field (e.g., `aud` or `jid`?). I would be fine to close this issue with that PR, for which I can accept authorship responsibility.

**Comment by OR13** [comment] 2021-05-24 21:22
@wyc sounds like a great reason not to support VP-JWT... the spec failed to address replay attack considerations for JWT... in either case, its not for us to solve that... we cannot alter the VC Data Model in this spec.

You might consider moving this issue to the VC Data Model repo or the vp-token repo... @awoie

**Comment by awoie** [comment] 2021-05-24 21:31
Without arguing for or against VP-JWT, those kind of things are by design outside of the VC Data Model spec. Same for LD-Proofs btw. You won't find a normative definition of `challenge` and `domain` (or even `nonce` as per LD-P) in the VC Data Model spec. JWTs use `nonce` and `aud` for that. In the same way as for LD-P VCs, there is also a non-normative example in the spec. JOSE people would get upset if you tell them JWTs don't have a mechanism for that.

Again, I'm not arguing for or against VP-JWT, just wanted to clarify.

**Comment by OR13** [comment] 2021-05-25 14:11
@awoie I agree, so for both VC-JWT and LD Proofs we don't need to define replay attack fields here...

**Comment by brentzundel** [comment] 2021-07-19 20:27
Discussed during a meeting 19 July 2021.
We feel this may be out of scope for this group. Closing for now.

**Closed by brentzundel** 2021-07-19 20:27 UTC
